name: Build and deploy frontend to Azure Web App - Ocorrencias-Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy frontend to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Ocorrencias-Frontend'
          slot-name: 'Production'
          package: ./frontend
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_014B3D9596A949ECAF35BC9230317A46 }}